<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Xbim.Essentials" Version="6.0.578" />
    <PackageReference Include="Xbim.Geometry" Version="5.1.820" />
    <PackageReference Include="Xbim.Tessellator" Version="6.0.521" />
  </ItemGroup>

</Project>
