<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <Compile Include="..\RhinoIfc\Export\ClassMapper.cs" Link="Export\ClassMapper.cs" />
    <Compile Include="..\RhinoIfc\Export\InstanceGraphTraversal.cs" Link="Export\InstanceGraphTraversal.cs" />
  </ItemGroup>
</Project>
