<Project Sdk="Microsoft.NET.Sdk">
  <PropertyGroup>
    <OutputType>Exe</OutputType>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
  </PropertyGroup>
  <ItemGroup>
    <PackageReference Include="Xbim.Essentials" Version="6.0.578" />
    <Compile Include="..\RhinoIfc\Export\ClassMapper.cs" Link="Export\ClassMapper.cs" />
    <Compile Include="..\RhinoIfc\Export\InstanceGraphTraversal.cs" Link="Export\InstanceGraphTraversal.cs" />
    <Compile Include="..\RhinoIfc\Export\PresentationLayerExporter.cs" Link="Export\PresentationLayerExporter.cs" />
    <Compile Include="..\RhinoIfc\Export\MappedRepresentationFactory.cs" Link="Export\MappedRepresentationFactory.cs" />
    <Compile Include="..\RhinoIfc\Export\ExportPostProcessing.cs" Link="Export\ExportPostProcessing.cs" />
  </ItemGroup>
</Project>
