<Project Sdk="Microsoft.NET.Sdk">

  <PropertyGroup>
    <TargetFramework>net48</TargetFramework>
    <LangVersion>latest</LangVersion>
    <Title>GH_RhinoIfc</Title>
    <Description>Grasshopper component for IFC4 export</Description>
    <Version>0.2.1</Version>
    <EnableDynamicLoading>true</EnableDynamicLoading>
    <AppendTargetFrameworkToOutputPath>false</AppendTargetFrameworkToOutputPath>
    <CopyLocalLockFileAssemblies>true</CopyLocalLockFileAssemblies>
  </PropertyGroup>

  <ItemGroup>
    <PackageReference Include="Grasshopper" Version="8.*">
      <PrivateAssets>all</PrivateAssets>
      <ExcludeAssets>runtime</ExcludeAssets>
    </PackageReference>

    <PackageReference Include="Xbim.Essentials" Version="6.0.578" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\RhinoIfc\RhinoIfc.csproj">
      <PrivateAssets>none</PrivateAssets>
    </ProjectReference>
  </ItemGroup>

</Project>
